# Generated by Django 4.2.7 on 2026-09-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='project',
            name='delivered_with',
            field=models.CharField(blank=True, help_text='Practice the project was delivered with, if any', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Design & Site Supervision', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project value in KES. Leave blank if not disclosed.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year_label',
            field=models.CharField(blank=True, help_text='Free text, e.g. "2024-2025" or "Ongoing"', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='projects/featured/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Likuyani, Kakamega County', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='services.service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='How was it solved?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'Under Construction'), ('proposed', 'Proposed / In Design')], default='completed', max_length=20),
        ),
    ]
