# Generated by Django 4.2.7 on 2026-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('design', 'Architectural Design'), ('build', 'Design & Build'), ('supervision', 'Construction Supervision'), ('renovation', 'Renovations & Extensions'), ('hospitality', 'Resort & Hospitality')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
    ]
